name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Build wordlist
        run: make wordlist

      - name: Build testing wordlists
        run: make test-wordlist
        
      - name: Commit and push changes
          run: |
            git config --global user.name "chutified"
            git config --global user.email "tommychu2256@gmail.com"
            git add -A
            git commit -m "Update wordlist databases [GitHub Action]"
            git push

#  test:
#    needs: [data]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16
#
#      - name: Clean up
#        run: go mod tidy
#
#      - name: Build
#        run: go build -v ./...
#
#      - name: Test
#        run: make test
#
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Build binaries
#        run: make build