name: Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Install node modules
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make npmi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          keep_files: false
          commit_message: 'deploy: Smart Passwd website'
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
